# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qpb.proto',
  package='qpb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tqpb.proto\x12\x03qpb\"\x1c\n\x0bIpv4Address\x12\r\n\x05value\x18\x01 \x02(\x07\"\x1c\n\x0bIpv6Address\x12\r\n\x05\x62ytes\x18\x01 \x02(\x0c\"G\n\tL3Address\x12\x1c\n\x02v4\x18\x01 \x01(\x0b\x32\x10.qpb.Ipv4Address\x12\x1c\n\x02v6\x18\x02 \x01(\x0b\x32\x10.qpb.Ipv6Address\")\n\x08L3Prefix\x12\x0e\n\x06length\x18\x01 \x02(\r\x12\r\n\x05\x62ytes\x18\x02 \x02(\x0c\"+\n\x0cIfIdentifier\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t*3\n\rAddressFamily\x12\x0e\n\nUNKNOWN_AF\x10\x00\x12\x08\n\x04IPV4\x10\x01\x12\x08\n\x04IPV6\x10\x02*?\n\x10SubAddressFamily\x12\x0f\n\x0bUNKNOWN_SAF\x10\x00\x12\x0b\n\x07UNICAST\x10\x01\x12\r\n\tMULTICAST\x10\x02*\x8b\x01\n\x08Protocol\x12\x11\n\rUNKNOWN_PROTO\x10\x00\x12\t\n\x05LOCAL\x10\x01\x12\r\n\tCONNECTED\x10\x02\x12\n\n\x06KERNEL\x10\x03\x12\n\n\x06STATIC\x10\x04\x12\x07\n\x03RIP\x10\x05\x12\t\n\x05RIPNG\x10\x06\x12\x08\n\x04OSPF\x10\x07\x12\x08\n\x04ISIS\x10\x08\x12\x07\n\x03\x42GP\x10\t\x12\t\n\x05OTHER\x10\n')
)

_ADDRESSFAMILY = _descriptor.EnumDescriptor(
  name='AddressFamily',
  full_name='qpb.AddressFamily',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_AF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPV4', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPV6', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_ADDRESSFAMILY)

AddressFamily = enum_type_wrapper.EnumTypeWrapper(_ADDRESSFAMILY)
_SUBADDRESSFAMILY = _descriptor.EnumDescriptor(
  name='SubAddressFamily',
  full_name='qpb.SubAddressFamily',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SAF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNICAST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTICAST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=292,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_SUBADDRESSFAMILY)

SubAddressFamily = enum_type_wrapper.EnumTypeWrapper(_SUBADDRESSFAMILY)
_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='qpb.Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_PROTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KERNEL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATIC', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIP', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIPNG', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OSPF', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISIS', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGP', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=358,
  serialized_end=497,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
UNKNOWN_AF = 0
IPV4 = 1
IPV6 = 2
UNKNOWN_SAF = 0
UNICAST = 1
MULTICAST = 2
UNKNOWN_PROTO = 0
LOCAL = 1
CONNECTED = 2
KERNEL = 3
STATIC = 4
RIP = 5
RIPNG = 6
OSPF = 7
ISIS = 8
BGP = 9
OTHER = 10



_IPV4ADDRESS = _descriptor.Descriptor(
  name='Ipv4Address',
  full_name='qpb.Ipv4Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='qpb.Ipv4Address.value', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=46,
)


_IPV6ADDRESS = _descriptor.Descriptor(
  name='Ipv6Address',
  full_name='qpb.Ipv6Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='qpb.Ipv6Address.bytes', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=76,
)


_L3ADDRESS = _descriptor.Descriptor(
  name='L3Address',
  full_name='qpb.L3Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v4', full_name='qpb.L3Address.v4', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v6', full_name='qpb.L3Address.v6', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=149,
)


_L3PREFIX = _descriptor.Descriptor(
  name='L3Prefix',
  full_name='qpb.L3Prefix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='qpb.L3Prefix.length', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='qpb.L3Prefix.bytes', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=192,
)


_IFIDENTIFIER = _descriptor.Descriptor(
  name='IfIdentifier',
  full_name='qpb.IfIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='qpb.IfIdentifier.index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='qpb.IfIdentifier.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=237,
)

_L3ADDRESS.fields_by_name['v4'].message_type = _IPV4ADDRESS
_L3ADDRESS.fields_by_name['v6'].message_type = _IPV6ADDRESS
DESCRIPTOR.message_types_by_name['Ipv4Address'] = _IPV4ADDRESS
DESCRIPTOR.message_types_by_name['Ipv6Address'] = _IPV6ADDRESS
DESCRIPTOR.message_types_by_name['L3Address'] = _L3ADDRESS
DESCRIPTOR.message_types_by_name['L3Prefix'] = _L3PREFIX
DESCRIPTOR.message_types_by_name['IfIdentifier'] = _IFIDENTIFIER
DESCRIPTOR.enum_types_by_name['AddressFamily'] = _ADDRESSFAMILY
DESCRIPTOR.enum_types_by_name['SubAddressFamily'] = _SUBADDRESSFAMILY
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ipv4Address = _reflection.GeneratedProtocolMessageType('Ipv4Address', (_message.Message,), dict(
  DESCRIPTOR = _IPV4ADDRESS,
  __module__ = 'qpb_pb2'
  # @@protoc_insertion_point(class_scope:qpb.Ipv4Address)
  ))
_sym_db.RegisterMessage(Ipv4Address)

Ipv6Address = _reflection.GeneratedProtocolMessageType('Ipv6Address', (_message.Message,), dict(
  DESCRIPTOR = _IPV6ADDRESS,
  __module__ = 'qpb_pb2'
  # @@protoc_insertion_point(class_scope:qpb.Ipv6Address)
  ))
_sym_db.RegisterMessage(Ipv6Address)

L3Address = _reflection.GeneratedProtocolMessageType('L3Address', (_message.Message,), dict(
  DESCRIPTOR = _L3ADDRESS,
  __module__ = 'qpb_pb2'
  # @@protoc_insertion_point(class_scope:qpb.L3Address)
  ))
_sym_db.RegisterMessage(L3Address)

L3Prefix = _reflection.GeneratedProtocolMessageType('L3Prefix', (_message.Message,), dict(
  DESCRIPTOR = _L3PREFIX,
  __module__ = 'qpb_pb2'
  # @@protoc_insertion_point(class_scope:qpb.L3Prefix)
  ))
_sym_db.RegisterMessage(L3Prefix)

IfIdentifier = _reflection.GeneratedProtocolMessageType('IfIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _IFIDENTIFIER,
  __module__ = 'qpb_pb2'
  # @@protoc_insertion_point(class_scope:qpb.IfIdentifier)
  ))
_sym_db.RegisterMessage(IfIdentifier)


# @@protoc_insertion_point(module_scope)
